### ISSUE TITLE
Possible to add a function to get the router IP address?

### ISSUE THREAD

**Issue by vallieres** [Shmoopi/iOS-System-Services#10]
Hello,

I just discovered iOS System Services and it's awesome!! Do you think it would be easy to add an extra fonction in SSNetworkInfo to get the router IP address?

Thanks!!

**Comment by Shmoopi** [comment]
Hello,

Sure, I don’t see why not.

Thanks!

**Comment by vallieres** [comment]
Do you know how to do this? I'm no Objective-C developer but I can play around with Cordova plugins and all so I can help do the grunt work ;)

**Comment by vallieres** [comment]
If you can point me to an example I would gladly do the change and issu a pull request.

**Comment by Shmoopi** [comment]
http://stackoverflow.com/questions/2113580/objective-c-how-to-fetch-the-router-address

That should work.  I appreciate the help and the enthusiasm!

Thanks!

**Comment by vallieres** [comment]
Hello,

I tried this thread too. And it does give out .255 address and it is not my current router address. 
I then tried to make the code in the comment work but SCDynamicStoreCreate does not exist under iOS.

I haven't tried the CustomRoute example, is that what you are referring to?

**Comment by Shmoopi** [comment]
Yeah, go ahead and try that, see what happens.  It may not take it.  It’s probably also a private api, but I’m not sure at the moment.

**Comment by vallieres** [comment]
Yeah, seems to be private apis, so that's a no go for me as it will land in an iOS app enventually.

I'm looking for a way to get the IP address of the router as in our setup it will expose an endpoint to fetch more information on the network devices currently connected.

Do you have another idea? ;) Thanks for your help!

**Comment by Shmoopi** [comment]
Seems like a pretty tricky subject.  I’m not able to find any solution or api that’ll work reliably for this.  The closest thing I could find was this posting:

http://stackoverflow.com/questions/2113580/objective-c-how-to-fetch-the-router-address

I’ll keep looking, but this seems like an issue that I’ll have to do more research on before coming up with a solution.

Thanks!

**Comment by vallieres** [comment]
I tried the getgateway example and was only able to retrieve the broadcast address.

I have the following:
IP Address is: 10.10.158.164
Wi-Fi Netmask Address is: 255.255.255.0 (from your code)
Wi-Fi Broadcast Address is: 10.10.158.255 (from the getgateway.c example)

And I know my router address is: 10.10.158.1

Is there a way for me to calculate the router IP or if you think of any other way to do this, I would appreciate it! I really want to get that damn address!! :P

**Comment by vallieres** [comment]
Hey! I ended finding a Netgear made iOS app on GitHub and extracted the code I needed to make myself a little plugin, which you can find here: https://github.com/vallieres/cordova-plugin-get-router-ip-address

I would be more than happy if you could check the code as I'm no Obj-C developer and I'm sure it's more complex than it should! You can also integrate it inside your own plugin which I'm already using at the moment on my project.

**Comment by Shmoopi** [comment]
Alright, I've incorporated some of the code into the project and it looks like it's working.  Let me know if you have any issues with it.

Thanks!
