### ISSUE TITLE
CocoaPods Availability

### ISSUE THREAD

**Issue by caofei10119** [Shmoopi/iOS-System-Services#13]

**Comment by Shmoopi** [comment]
Not yet

**Comment by mdsb100** [comment]
@Shmoopi Do you forget it ? Can u create submodule? I do not really want use all of the file.

**Comment by Shmoopi** [comment]
Hello @caofei10119 and @mdsb100,

Thank you for the reminder!  

We've added support for CocoaPods in the latest version and have cleaned up a lot of the code.  In addition, methods that do not work on iOS 9 have been deprecated.  

Thanks,
Shmoopi

**Comment by dnamicandresg** [comment]
Hey Shmoopi I'm trying to install this great library via Cocoapods and I'm getting a fatal error that says, "fatal: Remote branch 1.0.0 not found in upstream origin" below is the full log

Could yo be so kind to tell me if there is a work around for this issues?

Thanks in advance!
