### ISSUE TITLE
Is this app store safe?

### ISSUE THREAD

**Issue by kierancrown** [Shmoopi/iOS-System-Services#14]

**Comment by Shmoopi** [comment]
Hey @kierancrown, 

Currently, for iOS 8 and below - Yes.  In the future, for iOS 9 and above, probably not in it's current form.

Thanks,
Shmoopi

**Comment by Shmoopi** [comment]
Hello @kierancrown,

We've added support to show deprecated methods and validated that the library works as intended on iOS 9.  While we can't say for certain that all methods will work on all devices/versions, we've deprecated methods that clearly do not work for certain OS' and are in the process of removing support for methods that will not work in the future.

Thanks,
Shmoopi
