### ISSUE TITLE
duplicate symbol _JailbrokenChecks

### ISSUE THREAD

**Issue by arvindksharma** [Shmoopi/iOS-System-Services#17]
After adding this library to my project, I am getting this error.

I have tried all possible ways to debug it, but in-vain. When I remove the library, project builds fine, thus making sure that I have neither imported any .m file nor any other such duplicate linking.

I am in the middle of a very important project and stuck at dead end. Can you please help me in that as soon as possible.

Thanks,
Arvind
![jailbreak](https://cloud.githubusercontent.com/assets/965683/10882796/ba0a7916-8193-11e5-8967-180c90d4b9b7.jpg)

**Comment by Shmoopi** [comment]
Hello Arvind,

It appears that you are building the class files twice in your project.  You'll need to go through your build settings and build phases to determine how it is being accessed twice.  Here is a link that may help:  http://stackoverflow.com/questions/12988987/duplicate-symbols-for-architectures-in-xcode

Thanks,
Shmoopi
