### ISSUE TITLE
Mac Address

### ISSUE THREAD

**Issue by Dawnbrightsu** [Shmoopi/iOS-System-Services#18]
I am actually trying to find a way in which an app can get the mac address to make an indoor GPS (I mean if (phone connected to (mac address) then u are located in room 212, etc. but I notice that your app has the same problem I am having, the MAC address is 02:00:00:00 and I have been reading a lot about this problem with Apple new update, and I can't figure out a way to get it. 

If you can help me with that I will appreciate it. If you get the fix just push a new update on this Git Repository and I will check it.

Best Regards,
Gabriel Posada

**Comment by Shmoopi** [comment]
Hello Gabriel,

Apple has made it very clear that they will no longer be allowing developers to access unique identifiers of devices for App Store applications.  They've stopped allowing developers to read the MAC address from devices and are unlikely to allow it in the future.  If you'd like, you can file a bug report or request an enhancement to the SDK to allow this, but I don't think this will change anytime soon.

If there is a way to gather MAC address information without using private API's, I will update the class as soon as possible.

I hope that answers your question.

Thanks,
Shmoopi

**Comment by yumincode** [comment]
@Shmoopi
 hi,Shmoopi,
Did you find the way to get MAC address for App Store applications,if you solve the problem,please help me,thank you ...
