### ISSUE TITLE
fatal: Remote branch 1.0.0 not found in upstream origin

### ISSUE THREAD

**Issue by dnamicandresg** [Shmoopi/iOS-System-Services#20]
Hey guys I'm trying to install this great library via Cocoapods and I'm getting a fatal error that says, "fatal: Remote branch 1.0.0 not found in upstream origin" below is the full log

Could yo be so kind to tell me if there is a work around for this issues? 

Thanks in advance!

************************************************************************************************************
Installing SystemServices (1.0.0)

[!] Error installing SystemServices
[!] /usr/bin/git clone https://github.com/Shmoopi/iOS-System-Services.git /var/folders/r2/g26_5z3x19j23dv81rmpyycc0000gn/T/d20151201-51770-jtmznl --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/r2/g26_5z3x19j23dv81rmpyycc0000gn/T/d20151201-51770-jtmznl'...

warning: Could not find remote branch 1.0.0 to clone.

fatal: Remote branch 1.0.0 not found in upstream origin

************************************************************************************************************

**Comment by Shmoopi** [comment]
Hey @dnamicandresg,

Thanks for the heads-up!  

For some reason the tag didn't get pushed.  I'll fix it and let you know when it works.  Sorry about that!

Thanks,
Shmoopi

**Comment by Shmoopi** [comment]
@dnamicandresg,

We've pushed the new tag and it appears to be working.  Let me know if you have any other issues.

Thanks,
Shmoopi
