### ISSUE TITLE
Free memory is incorrect

### ISSUE THREAD

**Issue by tranhieutt** [Shmoopi/iOS-System-Services#23]
I use iPod 5 , RAM is 512 MB
When I call function: 
// Free Memory
-  (double)freeMemory:(BOOL)inPercent {
    // Find the total amount of free memory
    @try {
        // Set up the variables
        double TotalMemory = 0.00;
        vm_statistics_data_t vmStats;
        mach_msg_type_number_t infoCount = HOST_VM_INFO_COUNT;
        kern_return_t kernReturn = host_statistics(mach_host_self(), HOST_VM_INFO, (host_info_t)&vmStats, &infoCount);
        
        if(kernReturn != KERN_SUCCESS) {
            return -1;
        }
        
        // Check if the user wants it in percent
        if (inPercent) {
            // Percent
            // Convert to doubles
            double FM = [self totalMemory];
            double AM = ((vm_page_size * vmStats.free_count) / 1024.0) / 1024.0;
            // Get the percent
            TotalMemory = (AM * 100) / FM;
        } else {
            // Not in percent
            // Total Memory (formatted)
            TotalMemory = ((vm_page_size * vmStats.free_count) / 1024.0) / 1024.0;
        }
        
        // Check to make sure it's valid
        if (TotalMemory <= 0) {
            // Error, invalid memory value
            return -1;
        }
        
        // Completed Successfully
        return TotalMemory;
    }
    @catch (NSException *exception) {
        // Error
        return -1;
  }

in iOS-System-Services/System Services/Utilities/SSMemoryInfo.m file

free memory in result [TotalMemory] is not equal with free memory in Xcode.

For example, free memory in Xcode is 342 MB, but free memory in result function above is only 5.0 MB?
Why?
Please explain for me.
Thank you!

**Comment by Shmoopi** [comment]
Hello @tranhieutt,

Memory is not exact.  The total can fluctuate dramatically from device to device, and is known to be off.  We've tried to correct this by rounding the total amount of memory to the nearest 128mb - but that doesn't always work accurately.  It could also be that the memory you're seeing in Xcode is also slightly off, or reflects another side of free memory.  Or it could be a change in iOS 9, if that's what you're targeting.  Either way, the function should not be regarded as an exact amount.

Thanks,
Shmoopi
