### ISSUE TITLE
版本号获取的是build版本号 ？

### ISSUE THREAD

**Issue by gxhx2006** [Shmoopi/iOS-System-Services#28]
NSString *Version = [[NSBundle mainBundle] objectForInfoDictionaryKey:(NSString *)kCFBundleVersionKey];
well ，the version is build-version code！not version code！
it should be 
 NSString *Version = [[[NSBundle mainBundle] infoDictionary]objectForKey:@"CFBundleShortVersionString"];

**Comment by Shmoopi** [comment]
Thank you @gxhx2006, we fixed the bug.  [https://github.com/Shmoopi/iOS-System-Services/commit/f963a992cafb9cf61bdf64cbcb9acac193ef2a87](f963a99)
