### ISSUE TITLE
Why sharedServices return id? I can not use dot-notation syntax.

### ISSUE THREAD

**Issue by VincentSit** [Shmoopi/iOS-System-Services#34]
I have to do like:   

```
((SystemServices *)[SystemServices sharedServices]).allSystemInformation
```

Is this intentionally design?

**Comment by Shmoopi** [comment]
Hey @VincentSit,

Good catch!

That was not intentional.  It should be "instancetype".  I'll make sure that gets fixed.

Thanks,
Shmoopi

**Comment by VincentSit** [comment]
Thank you!
