### ISSUE TITLE
clarification question

### ISSUE THREAD

**Issue by sbswigart** [Shmoopi/iOS-System-Services#38]
```
        // Shouldn't get this far, return jailbroken
        return NOTJAIL;
```

In reference to the code found [here](https://github.com/Shmoopi/iOS-System-Services/blob/f963a992cafb9cf61bdf64cbcb9acac193ef2a87/System%20Services/Utilities/SSJailbreakCheck.m#L183) , in SSJailbreakCheck.m line 183, the comment and return value seem to contradict each other. Am I misreading the meaning of the comment, or is the return value wrong? As I'm reading the comment as in "shouldn't get this far, return jailbroken", yet it is returning the value of NOTJAIL. Thank you for any clarification.

**Comment by Shmoopi** [comment]
Hello @sbswigart,

Good find.  That comment is misleading.  The comment is incorrect, the return value is correct.  

I'll update that shortly.

Thanks,
Shmoopi

**Comment by Shmoopi** [comment]
Fixed
