### ISSUE TITLE
Will this Pass App Store Review?

### ISSUE THREAD

**Issue by victorstewart** [Shmoopi/iOS-System-Services#44]
Can this be used in production, aka an app in the App Store?

Interested in the Carrier info. I saw you use the CoreTelephony modules.. Pretty sure I read those are private.

**Comment by Shmoopi** [comment]
@victorstewart 

Good question!

We make no guarantees about production use, but there are a few applications that use this class in the App Store without issue.

The CoreTelephony framework is not private.
