### ISSUE TITLE
can you tell me why used memory + free memory do not equal all memory

### ISSUE THREAD

**Issue by joy0304** [Shmoopi/iOS-System-Services#46]
used memory = wired +active + inactive + purgeable memory

why do not equal ram 1024 ?

**Comment by Shmoopi** [comment]
Hi @joy0304,

Good question!  

Memory is not exact. The total can fluctuate dramatically from device to device, and is known to be off. We've tried to correct this by rounding the total amount of memory to the nearest 128mb - but that doesn't always work accurately.  The method should not be regarded as an exact amount.

Thanks,
Shmoopi
