### ISSUE TITLE
iOS 11 SDK: 'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by xpacificsoda** [Shmoopi/iOS-System-Services#47]
when I tried to build the code against iOS 11 sdk, xcode 9 beta 6, there is an error "'system' is unavailable: not available on iOS". Is there any function that can be replaced with 'system'?

**Comment by Shmoopi** [comment]
We've removed references to system in the latest version.

**Comment by xpacificsoda** [comment]
which commit includes this change?

**Comment by Shmoopi** [comment]
3ebee2d31f65675fc0aa726aa5b4f5b6c5f2be9a

Pod v2.0.0 includes these changes

**Comment by VincentSit** [comment]
@Shmoopi 

Thank you for your work.

Why does the minimum deployment target change to 9.0, do I have a way to use it in 8.0?

**Comment by Shmoopi** [comment]
@VincentSit 

Good question!  We are supporting n-2 OS releases to focus on new features.  Most features should work on iOS 8 with this release, but future releases may not.  

Version 1.1.1 is available if you'd like to continue to support iOS 6-10 devices.

Thanks!
