### ISSUE TITLE
Compile the error in xcode9

### ISSUE THREAD

**Issue by oceanfive** [Shmoopi/iOS-System-Services#49]
Hello，there is a error when i update to xcode9, below:

SSJailbreakCheck.m:268:13: error: 'system' is unavailable: not available on iOS
        if (system(0)) {
            ^

Showing Recent Issues
/Pods/SystemServices/System Services/Utilities/SSJailbreakCheck.m:268:13: 'system' is unavailable: not available on iOS

**Comment by oceanfive** [comment]
platform :ios, ‘7.0’

**Comment by Shmoopi** [comment]
Hello, 

Have you tried using the latest version?  system has been removed in version 2.0.0+.

Thanks!

**Comment by Moriquendi** [comment]
@Shmoopi 
I can't compile as well. The error I get is:
`SSNetworkInfo.m:19:10: 'net/route.h' file not found`
I use the latest version. Commit `3ebee2d31f65675fc0aa726aa5b4f5b6c5f2be9a`

**Comment by Moriquendi** [comment]
@Shmoopi 
I believe this:
```
#if !TARGET_IPHONE_SIMULATOR
#include <net/route.h>
#else
#include "route.h"
#endif
```

should be this

```
#if TARGET_IPHONE_SIMULATOR
#include <net/route.h>
#else
#include "route.h"
#endif
```

**Comment by yalamandarao** [comment]
@Shmoopi 
Can you please update Pod file base on @Moriquendi comments

**Comment by Shmoopi** [comment]
@yalamandarao 

I have found that the simulator does not find net/route.h and will fail to compile.  It may need to be only #include "route.h" 

Can someone test this?

**Comment by Moriquendi** [comment]
@Shmoopi Yup, I can confirm.
`#include "route.h"` is enough for both Simulator and the device.

**Comment by Shmoopi** [comment]
@Moriquendi Thanks!  I'll update shortly.

If anyone encounters issues with route.h, replacing the provided route.h file with /usr/include/net/route.h may help.

**Comment by Shmoopi** [comment]
2.0.1 address this issue.  Please let me know if there are any further issues related to this.

#b2cfcb50225dc61c7d738e82ed155b0e66239495

**Comment by yalamandarao** [comment]
@Shmoopi Thank you so much
