### ISSUE TITLE
<net/route.h> not found

### ISSUE THREAD

**Issue by omkaridx9** [Shmoopi/iOS-System-Services#51]
@Shmoopi I faced the issue. I have installed pod. When I try to run on simulator, it works. But when I try to run app on iPhone device, it fails saying <net/route.h> file not found in SSNetworkInfo.m file. I tried adding /usr/include/net to User Header Search Path. But it didn't work.

**Comment by Shmoopi** [comment]
Hello @omkaridx9 

This bug has been fixed with release 2.0.1.

Please let me know if you encounter any more issues.

Thanks!
